--SELECT * FROM ICECREAM_INFO  

--SELECT * FROM FIRST_HALF 

SELECT I.FLAVOR FROM ICECREAM_INFO I
JOIN FIRST_HALF F ON I.flavor = F.flavor
WHERE TOTAL_ORDER >= 3000 AND INGREDIENT_TYPE = 'fruit_based'