-- SELECT F.FILE_ID, F.FILE_EXT, F.FILE_NAME, B.BOARD_ID, B.VIEWS,
--         '/home/grep/src/' || FILE_ID || FILE_NAME || FILE_EXT AS "FILE_PATH"
-- FROM (SELECT *
--       FROM USED_GOODS_BOARD
--       ORDER BY VIEWS DESC
--       FETCH FIRST 1 ROWS ONLY) B
-- JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
SELECT '/home/grep/src/' || B.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS "FILE_PATH"
FROM (SELECT *
      FROM USED_GOODS_BOARD
      ORDER BY VIEWS DESC
      FETCH FIRST 1 ROWS ONLY) B
JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC
