SELECT RENTAL_HISTORY.HISTORY_ID, 
    ROUND(SUM(CAR.DAILY_FEE * (RENTAL_HISTORY.END_DATE - RENTAL_HISTORY.START_DATE + 1) 
        * (1 - (SELECT COALESCE(MAX(DISCOUNT_RATE), 0) / 100 
               FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
               WHERE CAR_TYPE = '트럭' 
               AND RENTAL_HISTORY.END_DATE - RENTAL_HISTORY.START_DATE + 1 >= 
                   CASE 
                       WHEN DURATION_TYPE = '7일 이상' THEN 7 
                       WHEN DURATION_TYPE = '30일 이상' THEN 30 
                       WHEN DURATION_TYPE = '90일 이상' THEN 90 
                   END
              )
        )
    )) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RENTAL_HISTORY ON CAR.CAR_ID = RENTAL_HISTORY.CAR_ID
WHERE CAR.CAR_TYPE = '트럭'
GROUP BY RENTAL_HISTORY.HISTORY_ID
ORDER BY FEE DESC, RENTAL_HISTORY.HISTORY_ID DESC;