SELECT AP.APNT_NO, PT.PT_NAME, AP.PT_NO, AP.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM PATIENT PT
JOIN APPOINTMENT AP ON PT.PT_NO = AP.PT_NO
JOIN DOCTOR DR ON AP.MDDR_ID = DR.DR_ID
WHERE AP.MCDP_CD = 'CS' 
AND AP.APNT_CNCL_YMD IS NULL
AND TO_CHAR(AP.APNT_YMD,'YYYY-MM-DD') = '2022-04-13'
ORDER BY AP.APNT_YMD;